### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by AnjaliSinghTW** [zllrunning/face-makeup.PyTorch#11]
I am getting above error on running !python makeup.py --img-path imgs/116.jpg command. I have followed all the instructions and am unable to detect the cause of the error. Can someone please help me out here.

**Comment by Hemanthhari2000** [comment]
could you be more specific about the error? or paste the screenshot of the error screen?

**Comment by AnjaliSinghTW** [comment]
As discussed in the mail,
The error was occurring because some of the methods used in code were not supported in google colab. We used cv2's methods instead of imutils' methods to resolve the error.

**Comment by AnjaliSinghTW** [comment]
Hi,

Thank you very much for replying.
It got resolved. I got it because in the code we were using cv2.imshow()
which is not supported in colab. So i just saved the output and opened it
by clicking
Sorry for the delayed response.

Thanks and Regards,
Anjali Singh
